# Generated by Django 6.1 on 2026-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
